topics = ['Numeros',
    'Antropología cultural', 
    'Arquitectura barroca', 
    'Arquitectura gótica', 
    'Arquitectura islámica', 
    'Arquitectura moderna', 
    'Arquitectura románica', 
    'Arte contemporáneo', 
    'Arte moderno', 
    'Arte renacentista', 
    'Biología evolutiva',
    'Biología molecular', 
    'Cannibal Corpse', 
    'Cibernética', 
    'Cine de animación', 
    'Cine de ciencia ficción', 
    'Cine de comedia', 
    'Cine de terror', 
    'Colombia', 
    'Demon Slayer', 
    'Desarrollo sostenible', 
    'Diseño gráfico', 
    'Diseño industrial', 
    'Dragon ball', 
    'Economía de mercado', 
    'Energía renovable', 
    'Escultura barroca', 
    'Evolución humana', 
    'Expansión del universo', 
    'Feminismo', 
    'Filosofía antigua', 
    'Filosofía de la mente', 
    'Filosofía moderna', 
    'Filosofía política', 
    'Fisiología humana', 
    'Física cinemática', 
    'Física clásica', 
    'Física de la materia condensada', 
    'Física de la relatividad', 
    'Física de partículas', 
    'Física nuclear', 
    'Física teórica', 
    'Geología del petróleo', 
    'Globalización', 
    'Guerra Fría', 
    'Guerras médicas', 
    'Historia del arte', 
    'Imperio alemán', 
    'Imperio austrohúngaro', 
    'Imperio azteca', 
    'Imperio bizantino', 
    'Imperio británico', 
    'Imperio chino', 
    'Imperio español', 
    'Imperio inca', 
    'Imperio maya', 
    'Imperio mogol',  
    'Imperio otomano', 
    'Imperio persa', 
    'Imperio romano', 
    'Imperio ruso', 
    'Ingeniería genética', 
    'Inteligencia artificial', 
    'Matrix', 
    'Medicina moderna', 
    'Nanotecnología', 
    'Neurociencia', 
    'Pintura impresionista', 
    'Pintura surrealista', 
    'Psicología cognitiva', 
    'Psicología del desarrollo', 
    'Psicología social', 
    'Publicidad', 
    'Reforma protestante', 
    'Renacimiento italiano', 
    'Revolución francesa', 
    'Revolución industrial', 
    'Revolución rusa', 
    'Revolución tecnológica', 
    'Revolución verde', 
    'Segunda Guerra Mundial', 
    'Sociología del género', 
    'Sociología del trabajo', 
    'Sociología urbana', 
    'Teatro griego', 
    'Teoría de juegos', 
    'Teoría de la complejidad', 
    'Teoría de la evolución', 
    'Teoría de la información', 
    'Teoría de la música', 
    'Teoría de la relatividad', 
    'Teoría de la relatividad especial', 
    'Teoría de la relatividad general', 
    'Teoría del Big Bang', 
    'Teoría del caos', 
    'Teoría del color', 
    'Teoría del diseño', 
    'Tercera revolución industrial', 
    'Testament', 
    'Trash Metal',
    'Tool']
